---
title: "Microbial Compositional in Brassica"
author: "Emily Wahly"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

# Load Environment 
```{r load-environ}
pacman::p_load(tidyverse, phyloseq, patchwork,dplyr,
               install = FALSE)

# Load colors and shapes 
source("/local/workdir/in_class_data/colors_and_shapes.R")

# Load in the scaled phyloseq object
load("/local/workdir/erw98/Brassica_Growth_2026/data/05_Ordination/scaled_physeq.RData")

# Look at the object 
scaled_physeq # scaled to 2,107 reads 
range(sample_sums(scaled_physeq))

# What is the range? 
max(sample_sums(scaled_physeq)) - min(sample_sums(scaled_physeq))
```

# Taxonomic Analysis

## Phylum Level 

```{r plot-phyla}
phylum_df <- 
  scaled_physeq %>%
  # Agglomerate all ASV/genus/family/order/class within a single phylum
  tax_glom(taxrank = "Phylum") %>%
  # Calculate the relative abundance
  transform_sample_counts(function(x) {x/sum(x)}) %>%
  # Create a dataframe from a phyloseq object
  psmelt()

# Take a look at the phylum_df
glimpse(phylum_df) 

# Top 10 most abundance phyla 
top10_phyla <- 
  phylum_df %>%
  dplyr::group_by(Phylum) %>%
  dplyr::summarize(mean_PercAbund = mean(Abundance), .groups = "drop") %>%
  dplyr::arrange(desc(mean_PercAbund)) %>%
  dplyr::slice_head(n = 10) %>%
  dplyr::pull(Phylum)

# Who are the top 10? 
top10_phyla
# create the plot 
phylum_df %>%
  dplyr::filter(Phylum %in% top10_phyla) %>%
  ggplot(aes(x = block, y = Abundance, 
             fill = Phylum, color = Phylum)) + 
  facet_wrap(Phylum~., scales = "free", nrow = 2) + 
  geom_jitter() + 
  theme_bw() + 
  scale_fill_manual(values = phylum_colors) + 
  scale_color_manual(values = phylum_colors) + 
  theme(legend.position = "none")
```





```{r asvs}
ASV_df <- 
  scaled_physeq %>%
  # Prune out ASVs that have fewer than ~1%! 
  ## LOOK AT HOW MANY ARE REMOVED! We scaled to 2,107 reads! 
  prune_taxa(taxa_sums(.) >= 211, .) %>%
  # agglomerate at the phylum level 
  tax_glom(taxrank = "ASV") %>% 
  # Transform counts to relative abundance 
  transform_sample_counts(function (x) {x/sum(x)}) %>%
  # Melt to a long format 
  psmelt() 

head(ASV_df)
# Make a list of phyla the top 10 ASVs in the Dataset
top15_ASVs <- 
  ASV_df %>%
  dplyr::group_by(ASV) %>%
  dplyr::summarize(mean_PercAbund = mean(Abundance)) %>%
  dplyr::arrange(-mean_PercAbund) %>%
  head(n = 15) %>%
  pull(ASV)

# show it 
top15_ASVs

#plot the top n asvs
ASV_df %>%
  dplyr::filter(ASV %in% top15_ASVs) %>%
  ggplot(aes(x = block, y = Abundance, fill = ASV, color = ASV)) + 
  facet_wrap(ASV~Genus, scales = "free", nrow = 3) + 
  # add the stacked bar 
  geom_jitter() +
  # change the colors to be our selected colors 
  theme_bw() + 
# scale_fill_viridis_d()+
  theme(legend.position = "bottom",
        axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
        axis.title.x = element_blank())

```


```{r by-phylum}
# Narrow in on a specific group
# Actinomycetota - y: abundance, x: salinity_group, dot plot + boxplot
pseudo_phylum_Block <- 
  phylum_df %>%
  dplyr::filter(Phylum == "Pseudomonadota") %>%
  # build the plot 
  ggplot(aes(x = block, y = Abundance, 
             fill = block, color = block)) + 
 # geom_boxplot(alpha = 0.5, outlier.shape = NA) + # outliers not plotted here in boxplot 
  geom_jitter() + 
  theme_bw() + 
  labs(title = "Pseudomonas Phylum") + 
    theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
          legend.position = "none")
# Statistically: Kruskall-Wallis followed by a Tukey's Posthoc test
# These are non-parametric (non-normal) stat tests 
pseudo_phylum_Block
bacillota_phylum_Block <- 
  phylum_df %>%
  dplyr::filter(Phylum == "Bacillota") %>%
  # build the plot 
  ggplot(aes(x = block, y = Abundance, 
             fill = block, color = block)) + 
 # geom_boxplot(alpha = 0.5, outlier.shape = NA) + # outliers not plotted here in boxplot 
  geom_jitter() + 
  theme_bw() + 
  labs(title = "Bacillota Phylum") + 
    theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1),
          legend.position = "none")
# Statistically: Kruskall-Wallis followed by a Tukey's Posthoc test
# These are non-parametric (non-normal) stat tests 

# CONTINUOUS 
# actino_phylum_salinity <- 
#   phylum_df %>%
#   dplyr::filter(Phylum == "Bacillota") %>%
#   ggplot(aes(x = block, y = Abundance)) + 
#   geom_point(aes(color = block)) + 
#    geom_jitter() + 
#   theme_bw() + 
#  # geom_smooth(method = "lm") + 
#   labs(title = "Massilia Phylum") + 
#  # scale_color_manual(values = salinity_colors) + 
#   theme(legend.position = "none")

# Collect both of the plots together into one 
pseudo_phylum_Block + bacillota_phylum_Block + 
  plot_layout(guides = "collect") +
  plot_annotation(tag_levels = "A")
```


```{r}
# Stacked area plot of top 10 phyla across blocks
df_area <- 
  scaled_physeq %>%
  tax_glom(taxrank = "Phylum") %>%
  transform_sample_counts(function(x) x / sum(x)) %>%
  psmelt() %>%
  group_by(block, Phylum) %>%
  summarise(Abundance = sum(Abundance), .groups = "drop")

df_area <- 
  df_area %>%
  filter(Phylum %in% top10_phyla) %>%
  mutate(block = factor(block, levels = sort(unique(block)))) %>%
  arrange(block)

ggplot(df_area, aes(x = block, y = Abundance, fill = Phylum)) +
  geom_col(position = "stack", color = "black", alpha = 0.9) +
#  scale_fill_manual(values = valid_colors) +
  theme_bw() +
  labs(title = "Community Composition of Top 10 Phyla Across Blocks",
       x = "Block",
       y = "Relative Abundance") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


